# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RCSceneExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for RCSceneExample
  
  pod 'RCSceneRadioRoom', :path => '../'
  pod 'RCSceneRoom', :path => '~/workspace/rongcloud-scene-room-ios'
  pod 'PLPlayerKit'
#  pod 'Kingfisher', '5.15.8'
  
end
